---

- name: Assert Dynamo DB configuration
  assert:
    that:
      - sansible_aws_dynamo_db_attribute_definitions is not none
      - sansible_aws_dynamo_db_billing_mode in ["PAY_PER_REQUEST", "PROVISIONED"]
      - sansible_aws_dynamo_db_key_schema is not none
      - sansible_aws_dynamo_db_region is not none
      - sansible_aws_dynamo_db_stack_name is not none
      - sansible_aws_dynamo_db_tags is not none

- name: Assert Dynamo DB payment/provision configuration
  assert:
    that:
      - sansible_aws_dynamo_db_provisioned_throughput_read is not none
      - sansible_aws_dynamo_db_provisioned_throughput_write is not none
  when: sansible_aws_dynamo_db_billing_mode == "PROVISIONED"

- name: Ensures Dynamo DB stack
  cloudformation:
    stack_name: "{{ sansible_aws_dynamo_db_stack_name }}"
    state: present
    region: "{{ sansible_aws_dynamo_db_region }}"
    tags: "{{ sansible_aws_dynamo_db_tags }}"
    template_body: "{{ lookup('template', '../templates/aws_dynamo_db.yaml.j2') }}"
    template_parameters:
      BillingMode: "{{ sansible_aws_dynamo_db_billing_mode }}"
  register: sansible_aws_dynamo_db_data
