---

- name: Converge
  hosts: localhost

  environment:
    EC2_URL: http://localhost:4566

  roles:
    - role: aws_dynamo_db
      sansible_aws_dynamo_db_attribute_definitions:
        - name: name
          type: S
        - name: version
          type: S
      sansible_aws_dynamo_db_billing_mode: PAY_PER_REQUEST
      sansible_aws_dynamo_db_key_schema:
        - name: name
          key_type: HASH
        - name: version
          key_type: RANGE
      sansible_aws_dynamo_db_region: eu-west-1
      sansible_aws_dynamo_db_stack_name: test-dynamo-db-on-demand
      sansible_aws_dynamo_db_table_name: test-dynamo-db-on-demand
      sansible_aws_dynamo_db_tags:
        Name: test-dynamo-db-on-demand

    - role: aws_dynamo_db
      sansible_aws_dynamo_db_attribute_definitions:
        - name: name
          type: S
        - name: version
          type: S
      sansible_aws_dynamo_db_billing_mode: PROVISIONED
      sansible_aws_dynamo_db_key_schema:
        - name: name
          key_type: HASH
        - name: version
          key_type: RANGE
      sansible_aws_dynamo_db_provisioned_throughput_read: 1
      sansible_aws_dynamo_db_provisioned_throughput_write: 1
      sansible_aws_dynamo_db_region: eu-west-1
      sansible_aws_dynamo_db_stack_name: test-dynamo-db-provisioned
      sansible_aws_dynamo_db_table_name: test-dynamo-db-provisioned
      sansible_aws_dynamo_db_tags:
        Name: test-dynamo-db-provisioned
